#!/usr/bin/python3
""" Script para generar tu Daily desde la terminal, y mandar a slack de una.
- Author: Alejo Prieto Dávalos
"""
from pathlib import Path
from argparse import ArgumentParser

def daily_commit(*, path_daily: Path, text: str) -> None:
    """ Guarda el texto de la daily en un txt."""
    with open(path_daily, "a+") as f:
        f.write(f"{text}\n")

def daily_push(*, path_daily: Path) -> None:
    """ Envía la daily por slack."""
    print("Pushing daily...")


def main():
    # Path donde se guardará la daily.
    path_daily = Path.home() / "__my_daily.txt"

    parser = ArgumentParser()
    parser.add_argument('-m', type=str)
    parser.add_argument('push', nargs='?', const='push')
    args = parser.parse_args()

    if args.m:
        daily_commit(path_daily=path_daily, text=args.m)
    elif args.push:
        daily_push(path_daily=path_daily)
    else:
        parser.error("Error: Usar `daily -m 'my daily'` o `daily push`")

if __name__ == "__main__":
    main()