from src.core.repositories.program_repository import ProgramRepository
from src.core.repositories.program_registry_repository import ProgramRegistryRepository

# Backward compatibility aliases.
ProgramBuildConfigRepository = ProgramRepository
ProgramConfigRepository = ProgramRegistryRepository
